CREATE DATABASE PetProject3;

CREATE TABLE Sensor(
                       id int primary key generated by default as identity primary key,
                       name varchar(100) not null unique
);

CREATE TABLE Measurement(
                            id int primary key generated by default as identity primary key,
                            value double precision not null,
                            raining boolean not null,
                            measurement_date_time timestamp not null,
                            sensor int references Sensor(id)
);

CREATE TABLE my_user(
                        id int primary key generated by default as identity,
                        username varchar(50) not null unique,
                        password varchar(100) not null,
                        role varchar(50)
);